version: '3.9'
services:
  server:
    build:
        context: ./server
    ports:
      - "5000:5000"
    environment:
      - ENVIRONMENT=dev
      - PORT=5000
      - DATABASE_URL=./db.json
  client:
    build:
        context: ./client
    ports:
      - "3000:5173"
    environment:
      - VITE_API_URL=http://localhost:5000
    depends_on:
      - server