name: CI

on:
  push:
    branches: [main]

jobs:
  server:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: server
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Start Server
        run: node index.js &
        timeout-minutes: 5
        env:
          PORT: 4000

  client:
    runs-on: ubuntu-latest
    needs: server
    defaults:
      run:
        working-directory: client
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install
        run: npm ci
      - name: Test
        run: npm run test
