name: CI

on:
  push:
    branches: [main]

jobs:
  server:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: server
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Start Server
        run: node index.js &
        env:
          PORT: 4000
        timeout-minutes: 5

  client:
    runs-on: ubuntu-latest
    needs: server
    defaults:
      run:
        working-directory: client
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Start client
        run: npm run dev &
        env:
          PORT: 5173

  e2e-tests:
    runs-on: ubuntu-latest
    needs: client
    defaults:
      run:
        working-directory: client
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: List directory structure
        run: ls -la
      - name: Verify package-lock.json existence
        run: ls -la package-lock.json || echo "package-lock.json not found!"
      - name: Install Dependencies
        run: npm ci
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          wait-on: "http://localhost:5173"
          wait-on-timeout: 300
          browser: chrome
