name: CI

on:
  push:
    branches: [main]

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js for Backend
        uses: actions/setup-node@v2
        with:
          node-version: "20"
      - name: Install Backend Dependencies
        run: npm install
        working-directory: server
      - name: Start Server
        run: node index.js &
        env:
          PORT: 4000
        working-directory: server
        timeout-minutes: 5

      # Frontend setup
      - name: Setup Node.js for Frontend
        uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Install Frontend Dependencies
        run: npm install
        working-directory: client
      - name: Start client
        run: npm run dev &
        env:
          PORT: 5173
        working-directory: client

      # E2E Tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          wait-on: "http://localhost:5173"
          wait-on-timeout: 300
          browser: chrome
        working-directory: client
